- name: Accept Android SDK Licenses & Build
      run: |
        # الموافقة التلقائية على جميع رخص Android SDK
        yes | android-update-sdk --accept-licenses || true
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # تشغيل التجميع تلقائياً واختيار yes على أي مطالبة
        yes | buildozer -v android debug
